import type { ReactNode } from "react";
import type { ComponentType } from "@/types/tool";
import type { ToolNodeProps } from "./nodes";
import {
  AudioPlayerNode,
  BadgeNode,
  ButtonGroupNode,
  ButtonNode,
  CanvasSceneNode,
  CardNode,
  ChartAreaNode,
  ChartBarNode,
  ChartDonutNode,
  ChartLineNode,
  ChartPieNode,
  ChartScatterNode,
  CheckboxNode,
  ChecklistNode,
  ClockNode,
  CodeEditorNode,
  ColorInputNode,
  ColumnNode,
  ContainerNode,
  CounterNode,
  DataTableNode,
  DateInputNode,
  DateTimeInputNode,
  DictationButtonNode,
  DividerNode,
  EmptyStateNode,
  FieldGroupNode,
  FilePickerNode,
  FormNode,
  HeadingNode,
  ImageNode,
  ListNode,
  MathBlockNode,
  MathInlineNode,
  MediaPickerNode,
  NumberInputNode,
  ProgressNode,
  QuizNode,
  RadioGroupNode,
  ResetButtonNode,
  RowNode,
  SelectNode,
  SliderNode,
  SpacerNode,
  StatNode,
  SubmitButtonNode,
  SvgCircleNode,
  SvgEllipseNode,
  SvgGroupNode,
  SvgLineNode,
  SvgPathNode,
  SvgRectNode,
  SvgSceneNode,
  SvgTextNode,
  SwitchNode,
  TableNode,
  TabsNode,
  TextAreaNode,
  TextInputNode,
  TextNode,
  TimeInputNode,
  UnsupportedNode,
  ValidationMessageNode,
} from "./nodes";

export const componentRegistry: Record<
  ComponentType,
  (props: ToolNodeProps) => ReactNode
> = {
  container: ContainerNode,
  row: RowNode,
  column: ColumnNode,
  card: CardNode,
  tabs: TabsNode,
  divider: DividerNode,
  spacer: SpacerNode,
  heading: HeadingNode,
  text: TextNode,
  badge: BadgeNode,
  image: ImageNode,
  emptyState: EmptyStateNode,
  textInput: TextInputNode,
  textArea: TextAreaNode,
  numberInput: NumberInputNode,
  select: SelectNode,
  checkbox: CheckboxNode,
  dateInput: DateInputNode,
  list: ListNode,
  checklist: ChecklistNode,
  table: TableNode,
  counter: CounterNode,
  progress: ProgressNode,
  stat: StatNode,
  button: ButtonNode,
  buttonGroup: ButtonGroupNode,
  quiz: QuizNode,
  clock: ClockNode,
  form: FormNode,
  fieldGroup: FieldGroupNode,
  radioGroup: RadioGroupNode,
  slider: SliderNode,
  switch: SwitchNode,
  colorInput: ColorInputNode,
  timeInput: TimeInputNode,
  dateTimeInput: DateTimeInputNode,
  filePicker: FilePickerNode,
  mediaPicker: MediaPickerNode,
  submitButton: SubmitButtonNode,
  resetButton: ResetButtonNode,
  validationMessage: ValidationMessageNode,
  svgScene: SvgSceneNode,
  svgRect: SvgRectNode,
  svgCircle: SvgCircleNode,
  svgEllipse: SvgEllipseNode,
  svgLine: SvgLineNode,
  svgPath: SvgPathNode,
  svgText: SvgTextNode,
  svgGroup: SvgGroupNode,
  chartLine: ChartLineNode,
  chartBar: ChartBarNode,
  chartPie: ChartPieNode,
  chartDonut: ChartDonutNode,
  chartArea: ChartAreaNode,
  chartScatter: ChartScatterNode,
  codeEditor: CodeEditorNode,
  mathInline: MathInlineNode,
  mathBlock: MathBlockNode,
  canvasScene: CanvasSceneNode,
  audioPlayer: AudioPlayerNode,
  dataTable: DataTableNode,
  // Legacy type: kept in ComponentTypeSchema so old tools parse, but not
  // generatable. DictationButtonNode is a compatibility fallback only.
  dictationButton: DictationButtonNode,
};

export function resolveComponent(
  type: string,
): (props: ToolNodeProps) => ReactNode {
  if (type in componentRegistry) {
    return componentRegistry[type as ComponentType];
  }
  return UnsupportedNode;
}
